# Generated by Django 2.0.4 on 2018-04-21 16:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Opublikować?')),
                ('notes', models.TextField(max_length=200, null=True, verbose_name='Info')),
                ('topic', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('lead', models.TextField(max_length=400, null=True, verbose_name='Lead')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='Treść')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenty',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wydawca')),
            ],
            options={
                'verbose_name': 'Wydanie',
                'verbose_name_plural': 'Wydania',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Imię')),
                ('surname', models.CharField(max_length=40, verbose_name='Nazwisko')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('alt_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telefon/Menadżer')),
                ('notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Notatki')),
                ('ocena', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True)),
            ],
            options={
                'verbose_name': 'Gość',
                'verbose_name_plural': 'Goście',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Imię')),
                ('surname', models.CharField(max_length=40, verbose_name='Nazwisko')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Prowadzący',
                'verbose_name_plural': 'Prowadzący',
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='hosts',
            field=models.ManyToManyField(related_name='editions', to='cms_body.Host', verbose_name='Prowadzący'),
        ),
        migrations.AddField(
            model_name='document',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cms_body.Edition', verbose_name='Wydanie'),
        ),
        migrations.AddField(
            model_name='document',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='documents', to='cms_body.Guest', verbose_name='Goście'),
        ),
    ]
