# Generated by Django 2.0 on 2018-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.TextField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
