# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0003_auto_20180329_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Wydawca', 'verbose_name_plural': 'Wydawcy'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'Wydanie', 'verbose_name_plural': 'Wydania'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Gość', 'verbose_name_plural': 'Goście'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Prowadzący', 'verbose_name_plural': 'Prowadzący'},
        ),
    ]
