# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 11:30
from __future__ import unicode_literals

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0004_auto_20180329_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
