# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0007_auto_20180329_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='wydanie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_body.Edition', verbose_name='Wydanie'),
        ),
    ]
