# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0008_document_wydanie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='wydanie',
            new_name='edition',
        ),
        migrations.AddField(
            model_name='document',
            name='guests',
            field=models.ManyToManyField(null=True, related_name='doc_guests', to='cms_body.Guest', verbose_name='Goście'),
        ),
    ]
