# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0009_auto_20180329_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='guests',
            field=models.ManyToManyField(related_name='doc_guests', to='cms_body.Guest', verbose_name='Goście'),
        ),
    ]
