# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0010_auto_20180329_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_body.Edition', verbose_name='documents'),
        ),
    ]
