# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0012_auto_20180329_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='tv_ready',
            field=models.IntegerField(choices=[(1, 'black'), (2, 'red'), (3, 'blue'), (4, 'yellow'), (5, 'green')], default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_authors', to='cms_body.Author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_editions', to='cms_body.Edition', verbose_name='Wydanie'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='hosts',
            field=models.ManyToManyField(related_name='host_progs', to='cms_body.Host', verbose_name='Prowadzący'),
        ),
    ]
