# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0014_auto_20180330_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='document',
            name='guests',
            field=models.ManyToManyField(blank=True, null=True, related_name='doc_guests', to='cms_body.Guest', verbose_name='Goście'),
        ),
    ]
