# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0015_auto_20180407_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='doc_guests', to='cms_body.Guest', verbose_name='Goście'),
        ),
    ]
