# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0017_document_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='alt_phone',
            field=models.CharField(max_length=128, null=True, verbose_name='Telefon/Menadżer'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tv_ready',
            field=models.IntegerField(choices=[(1, 'black'), (2, 'red'), (3, 'blue'), (4, 'yellow'), (5, 'green')], null=True),
        ),
    ]
