# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0018_auto_20180408_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telefon/Menadżer'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tv_ready',
            field=models.IntegerField(blank=True, choices=[(1, 'black'), (2, 'red'), (3, 'blue'), (4, 'yellow'), (5, 'green')], null=True),
        ),
    ]
