# Generated by Django 2.0.4 on 2018-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0020_auto_20180412_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
    ]
