# Generated by Django 2.0.4 on 2018-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0021_auto_20180412_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='tv_ready',
        ),
        migrations.AddField(
            model_name='guest',
            name='ocena',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True),
        ),
    ]
