# Generated by Django 2.0.4 on 2018-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0023_auto_20180413_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(max_length=400, null=True, verbose_name='Informacje'),
        ),
    ]
