# Generated by Django 2.0.4 on 2018-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0024_document_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(max_length=200, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
