# Generated by Django 2.0.4 on 2018-04-17 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0026_auto_20180417_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wydawca'),
        ),
    ]
