# Generated by Django 2.0.4 on 2018-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_body', '0027_auto_20180417_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Opublikować?'),
        ),
    ]
